# Generated by Django 5.2.1 on 2025-05-31 22:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SensorHumedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=100, unique=True)),
                ('ubicacion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('rol', models.CharField(choices=[('administrador', 'Administrador'), ('operador', 'Operador')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LecturaHumedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(help_text='Porcentaje de humedad (%)')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='api.sensorhumedad')),
            ],
        ),
        migrations.CreateModel(
            name='ZonaRiego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('area_m2', models.FloatField()),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zonas', to='api.cultivo')),
            ],
        ),
        migrations.AddField(
            model_name='sensorhumedad',
            name='zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensores', to='api.zonariego'),
        ),
        migrations.CreateModel(
            name='Riego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('cantidad_agua_litros', models.FloatField()),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riegos', to='api.zonariego')),
            ],
        ),
        migrations.CreateModel(
            name='PronosticoClima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('temperatura', models.FloatField()),
                ('precipitacion', models.FloatField(help_text='Precipitación esperada en mm')),
                ('humedad', models.FloatField()),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pronosticos', to='api.zonariego')),
            ],
        ),
    ]
